[package]
name = "controller"
version = "0.1.0"
edition = "2021"

[dependencies]
model = { path = "../model" }
view = { path = "../view" }
logger = { path = "../logger" }
config = { path = "../config" }
